[package]
name = "mini-torrent"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
rand = "0.8.5"
reqwest = "0.12.8"
sha1 = "0.10"
urlencoding = "2.1.3"
tokio = { version = "1.28", features = ["full"] }
bendy = "0.3.3"
